import { normalizeJob } from "@/lib/jobs/normalize";
import { deduplicateJobs } from "@/lib/jobs/deduplicate";
import type { Job, RawJob } from "./types";

function daysAgo(days: number, hours = 0): string {
  return new Date(Date.now() - days * 86_400_000 - hours * 3_600_000).toISOString();
}

const RAW_JOBS: Array<Omit<Job, "id">> = [
  {
    externalId: "mock-001",
    source: "mock",
    title: "Full Stack Developer — React & Node.js",
    company: { name: "Yassir", website: "https://yassir.com" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Build the delivery platform used by millions across North Africa. You'll own features end-to-end — from React UIs to the Node.js services behind them — with a product team that ships every week.",
    responsibilities: [
      "Design and ship product features in React/Next.js",
      "Build and maintain Node.js + MongoDB APIs",
      "Write tests and review code in a small senior team",
    ],
    requirements: [
      "3+ years full-stack development with JavaScript/TypeScript",
      "Strong React and Node.js fundamentals",
      "Comfort with MongoDB, SQL and Git",
    ],
    skills: ["react", "next.js", "node.js", "typescript", "mongodb", "docker", "git"],
    salary: { min: 18000, max: 26000, currency: "MAD" },
    publishedAt: daysAgo(1, 5),
    fetchedAt: new Date().toISOString(),
    url: "https://yassir.com/careers/full-stack",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-002",
    source: "mock",
    title: "Backend Engineer — Node.js",
    company: { name: "Anjori", website: "https://anjori.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Design the services that keep logistics moving. 100% remote-friendly team based in Morocco, building a platform that connects hauliers with freight from Europe to West Africa.",
    responsibilities: [
      "Build distributed services with Node.js and PostgreSQL",
      "Model complex pricing and routing domains",
      "Own reliability, observability, and testing",
    ],
    requirements: [
      "3+ years with Node.js and TypeScript",
      "Solid PostgreSQL and API design experience",
      "Nice to have: Python, Kafka, or map/geo experience",
    ],
    skills: ["node.js", "typescript", "postgresql", "rest apis", "docker", "kafka"],
    salary: { min: 15000, max: 22000, currency: "MAD" },
    publishedAt: daysAgo(4, 5),
    fetchedAt: new Date().toISOString(),
    url: "https://anjori.com/careers/backend",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-003",
    source: "mock",
    title: "Frontend Engineer — React",
    company: { name: "Chari", website: "https://chari.ma" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "Help our merchant dashboard reach thousands of shops across Morocco. A junior-friendly team where you'll grow fast writing real, customer-facing React day one.",
    responsibilities: [
      "Implement merchant-facing features in React",
      "Collaborate with design on our design system",
      "Ship, measure, and iterate with product",
    ],
    requirements: [
      "1+ year of React (or strong portfolio)",
      "Comfortable with HTML, CSS and JavaScript",
      "Curious and meticulous about UI details",
    ],
    skills: ["react", "typescript", "tailwind css", "css", "javascript"],
    salary: { min: 9000, max: 13000, currency: "MAD" },
    publishedAt: daysAgo(3, 12),
    fetchedAt: new Date().toISOString(),
    url: "https://chari.ma/careers/frontend",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-004",
    source: "mock",
    title: "Full Stack Engineer",
    company: { name: "ATLAN", website: "https://atlan.ma" },
    location: "Rabat",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Join a mission-driven team building civic tech for Moroccan government. Modern full-stack work (Next.js + Node) with real public impact.",
    responsibilities: [
      "Build civic digital services with Next.js and Node.js",
      "Work with designers and domain experts",
      "Contribute to open standards and accessibility",
    ],
    requirements: [
      "2+ years full-stack experience",
      "Next.js, TypeScript, and Node.js proficiency",
      "Empathy for users and good written communication",
    ],
    skills: ["next.js", "react", "typescript", "node.js", "postgresql", "tailwind css"],
    salary: { min: 12000, max: 18000, currency: "MAD" },
    publishedAt: daysAgo(7, 3),
    fetchedAt: new Date().toISOString(),
    url: "https://atlan.ma/careers/fullstack",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-005",
    source: "mock",
    title: "DevOps Engineer",
    company: { name: "Maroc Telecom", website: "https://iam.ma" },
    location: "Rabat",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Operate and evolve the infrastructure behind millions of customers. Kubernetes, CI/CD and platform engineering at national scale, Rabat.",
    responsibilities: [
      "Run Kubernetes clusters and CI/CD pipelines",
      "Automate infrastructure as code (Terraform)",
      "Mentor junior platform engineers",
    ],
    requirements: [
      "4+ years infrastructure/DevOps experience",
      "Kubernetes, Docker, and Terraform expertise",
      "Strong Linux and shell scripting",
    ],
    skills: ["kubernetes", "docker", "terraform", "ci/cd", "linux", "aws", "git"],
    salary: { min: 22000, max: 30000, currency: "MAD" },
    publishedAt: daysAgo(9, 6),
    fetchedAt: new Date().toISOString(),
    url: "https://iam.ma/careers/devops",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-006",
    source: "mock",
    title: "Mobile Engineer — React Native",
    company: { name: "Invyo", website: "https://invyo.io" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Build the app thousands of bookkeepers rely on every day. React Native + TypeScript, hybrid in Casablanca, small ownership-heavy team.",
    responsibilities: [
      "Ship features across the React Native app",
      "Pair with backend to design APIs",
      "Own release, crash-free rate, and QA loops",
    ],
    requirements: [
      "2+ years with React Native",
      "TypeScript and modern React patterns",
      "Experience with app stores and CI for mobile",
    ],
    skills: ["react native", "react", "typescript", "graphql", "mysql", "ci/cd"],
    salary: { min: 17000, max: 24000, currency: "MAD" },
    publishedAt: daysAgo(5, 9),
    fetchedAt: new Date().toISOString(),
    url: "https://invyo.io/careers/mobile",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-007",
    source: "mock",
    title: "Senior Software Engineer — Go",
    company: { name: "Numida", website: "https://numida.com" },
    location: "Remote",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Lead technical decisions on a fintech lending platform for African small businesses. Remote across Africa, generous budget, real ownership.",
    responsibilities: [
      "Architect and build Go microservices",
      "Design financial-grade data models",
      "Set engineering standards and review culture",
    ],
    requirements: [
      "5+ years software engineering, with Go",
      "Deep experience with PostgreSQL and distributed systems",
      "Experience designing reliable, tested systems",
    ],
    skills: ["go", "postgresql", "docker", "kubernetes", "aws", "typescript"],
    salary: { min: 4500, max: 6500, currency: "USD" },
    publishedAt: daysAgo(2, 8),
    fetchedAt: new Date().toISOString(),
    url: "https://numida.com/careers/go",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-008",
    source: "mock",
    title: "Frontend Developer (Vue.js)",
    company: { name: "Zowity", website: "https://zowity.ma" },
    location: "Marrakech",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Craft delightful web experiences for a tourism platform growing across the MENA region. Onsite Marrakech with a warm, design-loving team.",
    responsibilities: [
      "Build features in Vue 3 + Nuxt",
      "Own UI quality, a11y, and performance",
      "Work closely with product and design",
    ],
    requirements: [
      "2+ years Vue or strong React background",
      "Solid SCSS/CSS and design sensitivity",
      "Nice to have: Nuxt, TypeScript",
    ],
    skills: ["vue.js", "javascript", "typescript", "css", "tailwind css"],
    salary: { min: 12000, max: 17000, currency: "MAD" },
    publishedAt: daysAgo(11, 2),
    fetchedAt: new Date().toISOString(),
    url: "https://zowity.ma/careers/vue",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-009",
    source: "mock",
    title: "Data Scientist",
    company: { name: "Kifal", website: "https://kifal.com" },
    location: "Rabat",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Turn streaming data into decisions for a growing logistics group. Real datasets, real impact, hybrid in Rabat.",
    responsibilities: [
      "Build and evaluate ML models on logistics data",
      "Own feature pipelines from raw to production",
      "Communicate insights to business stakeholders",
    ],
    requirements: [
      "2+ years in data science / ML",
      "Python, pandas, scikit-learn proficiency",
      "Strong SQL and data storytelling",
    ],
    skills: ["python", "machine learning", "sql", "data science", "pandas", "scikit-learn"],
    salary: { min: 16000, max: 22000, currency: "MAD" },
    publishedAt: daysAgo(6, 4),
    fetchedAt: new Date().toISOString(),
    url: "https://kifal.com/careers/data-scientist",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-010",
    source: "mock",
    title: "Software Engineer — Python",
    company: { name: "Cloudrizon", website: "https://cloudrizon.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Help African enterprises adopt the cloud. You'll write Python alongside a distributed team improving tools thousands of engineers use.",
    responsibilities: [
      "Develop cloud tooling and SDKs in Python",
      "Integrate with major cloud providers",
      "Write thorough tests and documentation",
    ],
    requirements: [
      "3+ years Python engineering",
      "Solid understanding of REST APIs and cloud",
      "Good written English for async collaboration",
    ],
    skills: ["python", "aws", "rest apis", "docker", "github", "cloud"],
    salary: { min: 18000, max: 26000, currency: "MAD" },
    publishedAt: daysAgo(8, 10),
    fetchedAt: new Date().toISOString(),
    url: "https://cloudrizon.com/careers/python",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-011",
    source: "mock",
    title: "QA Automation Engineer",
    company: { name: "TibiMar Service", website: "https://tibimar.ma" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "Guard the quality of a platform used across Morocco. A great first QA automation role with a supportive team and clear growth path.",
    responsibilities: [
      "Own and grow the E2E test suite (Playwright)",
      "Pair with engineers on testability",
      "Report and triage quality signals",
    ],
    requirements: [
      "1+ year testing or junior dev experience",
      "JavaScript and basic automation knowledge",
      "Detail-oriented, methodical, curious",
    ],
    skills: ["javascript", "playwright", "testing", "git", "typescript"],
    salary: { min: 8000, max: 11500, currency: "MAD" },
    publishedAt: daysAgo(13, 5),
    fetchedAt: new Date().toISOString(),
    url: "https://tibimar.ma/careers/qa",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-012",
    source: "mock",
    title: "Product Manager — Marketplace",
    company: { name: "Zawya", website: "https://zawya.ma" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Shape the roadmap of a fast-growing e-commerce marketplace. Blend of discovery, data, and delivery, hybrid in Casablanca.",
    responsibilities: [
      "Own the marketplace discovery roadmap",
      "Run discovery with merchants and buyers",
      "Define success metrics and experiments",
    ],
    requirements: [
      "2+ years as a product manager",
      "Comfortable with data and A/B testing",
      "Excellent communication in French/English",
    ],
    skills: ["product management", "agile", "sql", "figma", "data analysis"],
    salary: { min: 14000, max: 20000, currency: "MAD" },
    publishedAt: daysAgo(15, 3),
    fetchedAt: new Date().toISOString(),
    url: "https://zawya.ma/careers/pm",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-013",
    source: "mock",
    title: "Full Stack Developer (Laravel)",
    company: { name: "Bghla Partners", website: "https://beghlapartners.com" },
    location: "Tangier",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Power a SaaS used across Morocco's ports and logistics. Laravel + Vue with a pragmatic team that ships, hybrid in Tangier.",
    responsibilities: [
      "Build product features with Laravel and Vue",
      "Design MySQL schemas and APIs",
      "Maintain and improve a monolith with care",
    ],
    requirements: [
      "3+ years with PHP / Laravel",
      "Vue.js and MySQL experience",
      "Testing mindset and clean code habits",
    ],
    skills: ["php", "laravel", "vue.js", "mysql", "javascript", "docker"],
    salary: { min: 14000, max: 19000, currency: "MAD" },
    publishedAt: daysAgo(17, 6),
    fetchedAt: new Date().toISOString(),
    url: "https://beghlapartners.com/careers/laravel",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-014",
    source: "mock",
    title: "Machine Learning Engineer",
    company: { name: "MedZ", website: "https://medz.ma" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Deploy ML at industrial scale for a Moroccan energy leader. Production ML, computer vision, and big data, onsite Casablanca.",
    responsibilities: [
      "Build and deploy computer-vision models",
      "Run experiments and manage model lifecycle",
      "Collaborate with engineering on production systems",
    ],
    requirements: [
      "4+ years in ML engineering",
      "Python, PyTorch/TensorFlow, CV experience",
      "Experience deploying models to production",
    ],
    skills: ["python", "machine learning", "computer vision", "pytorch", "tensorflow", "docker"],
    salary: { min: 24000, max: 32000, currency: "MAD" },
    publishedAt: daysAgo(19, 1),
    fetchedAt: new Date().toISOString(),
    url: "https://medz.ma/careers/ml",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-015",
    source: "mock",
    title: "Backend Engineer — Java/Spring",
    company: { name: "Attijariwafa Bank", website: "https://attijariwafa.com" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Design the systems behind Morocco's leading bank. Java/Spring, distributed transactions, and serious scale, onsite Casablanca.",
    responsibilities: [
      "Architect and build Spring Boot services",
      "Design highly-available transaction systems",
      "Mentor engineers and uphold standards",
    ],
    requirements: [
      "5+ years Java / Spring experience",
      "Distributed systems and SQL expertise",
      "Banking/fintech domain is a plus",
    ],
    skills: ["java", "spring", "sql", "microservices", "postgresql", "docker"],
    salary: { min: 25000, max: 34000, currency: "MAD" },
    publishedAt: daysAgo(12, 7),
    fetchedAt: new Date().toISOString(),
    url: "https://attijariwafa.com/careers/java",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-016",
    source: "mock",
    title: "WordPress Developer",
    company: { name: "WeBaaB", website: "https://webaab.ma" },
    location: "Marrakech",
    workplaceType: "onsite",
    employmentType: "contract",
    experienceLevel: "junior",
    description:
      "Build custom WordPress sites for international clients. Contract role, Marrakech, perfect for a meticulous junior dev.",
    responsibilities: [
      "Build custom themes and plugins",
      "Translate designs to pixel-perfect sites",
      "Handle performance and SEO basics",
    ],
    requirements: [
      "1+ year WordPress/PHP experience",
      "HTML/CSS/JS fundamentals",
      "Attention to detail and client empathy",
    ],
    skills: ["php", "wordpress", "html", "css", "javascript", "mysql"],
    salary: { min: 7000, max: 11000, currency: "MAD" },
    publishedAt: daysAgo(21, 4),
    fetchedAt: new Date().toISOString(),
    url: "https://webaab.ma/careers/wordpress",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-017",
    source: "mock",
    title: "Data Engineer",
    company: { name: "Chari", website: "https://chari.ma" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Own the data platform for a fast-scaling commerce fintech. Pipelines, warehouses, and trustworthy metrics, hybrid in Casablanca.",
    responsibilities: [
      "Build ETL/ELT pipelines (Airflow, dbt)",
      "Design the analytics warehouse (BigQuery)",
      "Enable analytics across the company",
    ],
    requirements: [
      "2+ years data engineering",
      "SQL, Python, and pipeline tooling",
      "dbt/Airflow and cloud experience",
    ],
    skills: ["sql", "python", "airflow", "dbt", "bigquery", "aws", "data engineering"],
    salary: { min: 15000, max: 21000, currency: "MAD" },
    publishedAt: daysAgo(10, 11),
    fetchedAt: new Date().toISOString(),
    url: "https://chari.ma/careers/data-engineer",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-018",
    source: "mock",
    title: "IT Support Engineer",
    company: { name: "OCP Group", website: "https://ocpgroup.ma" },
    location: "Khouribga",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "entry",
    description:
      "Launch your IT career at industrial scale. End-user and systems support across sites, with structured training. Onsite Khouribga.",
    responsibilities: [
      "Provide end-user support (laptops, VPN, SaaS)",
      "Maintain hardware inventory and onboarding",
      "Escalate and document issues properly",
    ],
    requirements: [
      "IT fundamentals or a relevant degree",
      "Windows, networking and troubleshooting",
      "Service-minded and reliable",
    ],
    skills: ["windows", "networking", "troubleshooting", "linux", "active directory"],
    salary: { min: 8000, max: 10500, currency: "MAD" },
    publishedAt: daysAgo(14, 8),
    fetchedAt: new Date().toISOString(),
    url: "https://ocpgroup.ma/careers/it-support",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-019",
    source: "mock",
    title: "Software Engineering Intern — Frontend",
    company: { name: "Invyo", website: "https://invyo.io" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "internship",
    experienceLevel: "entry",
    description:
      "A paid 6-month internship building real product with real mentorship. React + TypeScript, hybrid in Casablanca — PFAF-endorsed.",
    responsibilities: [
      "Build UI with React and TypeScript",
      "Learn code review, testing, and shipping",
      "Pair with senior engineers daily",
    ],
    requirements: [
      "Solid HTML/CSS/JS fundamentals",
      "Basic React and Git knowledge",
      "Eager to learn and ask questions",
    ],
    skills: ["react", "typescript", "javascript", "html", "css", "git"],
    salary: { min: 4000, max: 6000, currency: "MAD" },
    publishedAt: daysAgo(2, 3),
    fetchedAt: new Date().toISOString(),
    url: "https://invyo.io/careers/intern",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-020",
    source: "mock",
    title: "Senior Frontend Engineer",
    company: { name: "Vulpi", website: "https://vulpi.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Own the frontend of a remote-first dev-agency product. Design systems, performance, and team leadership, fully remote from Morocco.",
    responsibilities: [
      "Lead frontend architecture and design system",
      "Mentor a distributed team of engineers",
      "Set bar for performance and accessibility",
    ],
    requirements: [
      "5+ years React/TypeScript",
      "Design systems and testing experience",
      "Remote-leadership track record",
    ],
    skills: ["react", "typescript", "next.js", "tailwind css", "testing", "figma"],
    salary: { min: 900, max: 1400, currency: "USD" },
    publishedAt: daysAgo(16, 9),
    fetchedAt: new Date().toISOString(),
    url: "https://vulpi.com/careers/senior-frontend",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-021",
    source: "mock",
    title: "Security Engineer",
    company: { name: "MedZ", website: "https://medz.ma" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Harden industrial and cloud systems for a Moroccan energy leader. AppSec, infrastructure, and incident response, onsite Casablanca.",
    responsibilities: [
      "Run security reviews and threat modeling",
      "Implement cloud and app security controls",
      "Lead incident response and readiness",
    ],
    requirements: [
      "4+ years security engineering",
      "Cloud (AWS) and application security",
      "Strong Linux and scripting",
    ],
    skills: ["security", "aws", "linux", "cloud", "python", "networking"],
    salary: { min: 24000, max: 32000, currency: "MAD" },
    publishedAt: daysAgo(18, 6),
    fetchedAt: new Date().toISOString(),
    url: "https://medz.ma/careers/security",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-022",
    source: "mock",
    title: "Full Stack Developer (PHP)",
    company: { name: "DataQuery", website: "https://dataquery.ma" },
    location: "Rabat",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "Join a consultancy building web products for clients across Europe. PHP + JS, Rabat, with a learning-first culture.",
    responsibilities: [
      "Build client features with PHP and JS",
      "Write clean, tested, reviewable code",
      "Grow into a full-stack owner over time",
    ],
    requirements: [
      "1+ year PHP or strong web dev",
      "SQL and JavaScript fundamentals",
      "Great communication and reliability",
    ],
    skills: ["php", "javascript", "mysql", "html", "css", "git"],
    salary: { min: 9000, max: 13000, currency: "MAD" },
    publishedAt: daysAgo(20, 5),
    fetchedAt: new Date().toISOString(),
    url: "https://dataquery.ma/careers/php",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-023",
    source: "mock",
    title: "UX/UI Designer",
    company: { name: "Zawya", website: "https://zawya.ma" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Design flows people love for a leading Moroccan marketplace. From research to high-fidelity UI, hybrid in Casablanca.",
    responsibilities: [
      "Own end-to-end design for core flows",
      "Run usability research and testing",
      "Maintain and extend the design system",
    ],
    requirements: [
      "2+ years UX/UI design",
      "Figdom with Figma and prototyping",
      "Portfolio showing shipped work",
    ],
    skills: ["figma", "ui/ux", "prototyping", "user research", "design systems"],
    salary: { min: 13000, max: 18000, currency: "MAD" },
    publishedAt: daysAgo(22, 3),
    fetchedAt: new Date().toISOString(),
    url: "https://zawya.ma/careers/designer",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-024",
    source: "mock",
    title: "iOS Engineer — Swift",
    company: { name: "Chari", website: "https://chari.ma" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Build the mobile experience for merchants across Morocco. Swift + iOS, hybrid Casablanca, small high-output team.",
    responsibilities: [
      "Develop iOS features in Swift/SwiftUI",
      "Own release and App Store process",
      "Collaborate on API and UX decisions",
    ],
    requirements: [
      "2+ years iOS development",
      "Swift, UIKit/SwiftUI proficiency",
      "Care for craft and performance",
    ],
    skills: ["swift", "ios", "swiftui", "xcode", "git"],
    salary: { min: 15000, max: 21000, currency: "MAD" },
    publishedAt: daysAgo(23, 7),
    fetchedAt: new Date().toISOString(),
    url: "https://chari.ma/careers/ios",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-025",
    source: "mock",
    title: "Cloud Engineer",
    company: { name: "Cloudrizon", website: "https://cloudrizon.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Design and automate cloud infrastructure for enterprises in Africa. Terraform, AWS/GCP, remote from Morocco.",
    responsibilities: [
      "Build reusable Terraform modules",
      "Operate multi-cloud environments safely",
      "Advise clients on architecture",
    ],
    requirements: [
      "4+ years cloud engineering",
      "AWS and Terraform expertise",
      "Strong Kubernetes and networking",
    ],
    skills: ["aws", "terraform", "kubernetes", "docker", "linux", "gcp"],
    salary: { min: 1200, max: 1800, currency: "USD" },
    publishedAt: daysAgo(25, 2),
    fetchedAt: new Date().toISOString(),
    url: "https://cloudrizon.com/careers/cloud",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-026",
    source: "mock",
    title: "Product Designer",
    company: { name: "Kifal", website: "https://kifal.com" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Set the design bar for a logistics platform scaling across Africa. Own product design end-to-end, onsite Casablanca.",
    responsibilities: [
      "Own product design across the platform",
      "Build and evolve the design system",
      "Lead design cross-functional projects",
    ],
    requirements: [
      "4+ years product design",
      "Figma mastery and systems thinking",
      "Strong portfolio and communication",
    ],
    skills: ["figma", "ui/ux", "design systems", "prototyping", "user research"],
    salary: { min: 17000, max: 23000, currency: "MAD" },
    publishedAt: daysAgo(26, 5),
    fetchedAt: new Date().toISOString(),
    url: "https://kifal.com/careers/product-designer",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-027",
    source: "mock",
    title: "Backend Engineer — Go (junior)",
    company: { name: "Numida", website: "https://numida.com" },
    location: "Remote",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "A junior-friendly Go role with structured mentorship on a real fintech product. Remote across Africa.",
    responsibilities: [
      "Write Go APIs alongside senior engineers",
      "Learn testing, code review, and design",
      "Own small features end to end",
    ],
    requirements: [
      "Strong CS fundamentals",
      "Some Go, or strong Python/Java",
      "SQL and API basics",
    ],
    skills: ["go", "postgresql", "git", "sql", "python"],
    salary: { min: 1500, max: 2400, currency: "USD" },
    publishedAt: daysAgo(4, 11),
    fetchedAt: new Date().toISOString(),
    url: "https://numida.com/careers/go-junior",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-028",
    source: "mock",
    title: "Full Stack Developer — Next.js",
    company: { name: "Vimigo", website: "https://vimigo.io" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "Join a product studio building for international clients. Next.js + TypeScript, remote from Morocco, fast learning loop.",
    responsibilities: [
      "Ship features in Next.js and TypeScript",
      "Build with our component library",
      "Learn from code reviews and pairing",
    ],
    requirements: [
      "1+ year Next.js/React",
      "TypeScript and Tailwind comfort",
      "Remote-friendly communication",
    ],
    skills: ["next.js", "react", "typescript", "tailwind css", "postgresql", "git"],
    salary: { min: 10000, max: 15000, currency: "MAD" },
    publishedAt: daysAgo(1, 9),
    fetchedAt: new Date().toISOString(),
    url: "https://vimigo.io/careers/nextjs",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-029",
    source: "mock",
    title: "DevOps Engineer",
    company: { name: "Anjori", website: "https://anjori.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Own CI/CD and infrastructure for a logistics platform. Remote Morocco, Kubernetes-first, high-trust team.",
    responsibilities: [
      "Manage Kubernetes clusters and CI pipelines",
      "Automate releases with Terraform",
      "Improve observability and incident response",
    ],
    requirements: [
      "3+ years DevOps/SRE",
      "Kubernetes, Docker, Terraform",
      "Strong scripting and Linux",
    ],
    skills: ["kubernetes", "docker", "terraform", "ci/cd", "linux", "grafana", "prometheus"],
    salary: { min: 17000, max: 24000, currency: "MAD" },
    publishedAt: daysAgo(7, 8),
    fetchedAt: new Date().toISOString(),
    url: "https://anjori.com/careers/devops",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-030",
    source: "mock",
    title: "React Native Engineer",
    company: { name: "Yassir", website: "https://yassir.com" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Build the apps millions of North Africans use to order, ride, and pay. React Native + TypeScript, hybrid Casablanca.",
    responsibilities: [
      "Build features across iOS and Android",
      "Optimize performance and network usage",
      "Ship with quality and confidence",
    ],
    requirements: [
      "2+ years React Native",
      "TypeScript and state management",
      "App-store release experience",
    ],
    skills: ["react native", "react", "typescript", "javascript", "git", "ci/cd"],
    salary: { min: 17000, max: 25000, currency: "MAD" },
    publishedAt: daysAgo(3, 6),
    fetchedAt: new Date().toISOString(),
    url: "https://yassir.com/careers/react-native",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-031",
    source: "mock",
    title: "Technical Project Manager",
    company: { name: "ATLAN", website: "https://atlan.ma" },
    location: "Rabat",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Bridge teams and timelines for civic digital services in Morocco. Hybrid Rabat, meaningful mission.",
    responsibilities: [
      "Own delivery of digital-service projects",
      "Coordinate engineers, design, and stakeholders",
      "Track risk, scope, and quality",
    ],
    requirements: [
      "2+ years technical project management",
      "Agile/Scrum experience",
      "Great written communication",
    ],
    skills: ["agile", "scrum", "jira", "project management", "sql", "figma"],
    salary: { min: 14000, max: 20000, currency: "MAD" },
    publishedAt: daysAgo(24, 4),
    fetchedAt: new Date().toISOString(),
    url: "https://atlan.ma/careers/tpm",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-032",
    source: "mock",
    title: "Data Analyst",
    company: { name: "Maroc Telecom", website: "https://iam.ma" },
    location: "Rabat",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "Analyze usage across millions of subscribers securityably. SQL, dashboards, insights. Onsite Rabat.",
    responsibilities: [
      "Build SQL analyses and dashboards",
      "Partner with product on metrics",
      "Communicate insights to leaders",
    ],
    requirements: [
      "1+ year analytics experience",
      "Strong SQL and Excel/BI",
      "Clear communication",
    ],
    skills: ["sql", "excel", "power bi", "data analysis", "python"],
    salary: { min: 9000, max: 13000, currency: "MAD" },
    publishedAt: daysAgo(9, 1),
    fetchedAt: new Date().toISOString(),
    url: "https://iam.ma/careers/data-analyst",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-033",
    source: "mock",
    title: "Senior Frontend Engineer — Design Systems",
    company: { name: "Vulpi", website: "https://vulpi.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Build and lead the design system across a portfolio of products. Remote Morocco, systems-thinker welcome.",
    responsibilities: [
      "Own token/component architecture",
      "Drive adoption and contribution guides",
      "Raise quality across multiple products",
    ],
    requirements: [
      "5+ years React/TS",
      "Design-system and a11y depth",
      "Cross-team influence",
    ],
    skills: ["react", "typescript", "tailwind css", "design systems", "a11y", "testing"],
    salary: { min: 3500, max: 5000, currency: "USD" },
    publishedAt: daysAgo(28),
    fetchedAt: new Date().toISOString(),
    url: "https://vulpi.com/careers/design-systems",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-034",
    source: "mock",
    title: "Junior Software Engineer",
    company: { name: "TibiMar Service", website: "https://tibimar.ma" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "junior",
    description:
      "Kickstart your engineering career on a platform used across Morocco. Structured onboarding, mentoring, onsite Casablanca.",
    responsibilities: [
      "Ship product features with the team",
      "Learn our stack: TypeScript, Node, React",
      "Grow through reviews and mentoring",
    ],
    requirements: [
      "Strong fundamentals (data structures, APIs)",
      "Some TypeScript/JavaScript",
      "Curiosity and reliability",
    ],
    skills: ["typescript", "javascript", "react", "node.js", "sql", "git"],
    salary: { min: 8000, max: 12000, currency: "MAD" },
    publishedAt: daysAgo(6, 6),
    fetchedAt: new Date().toISOString(),
    url: "https://tibimar.ma/careers/junior",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-035",
    source: "mock",
    title: "QA Engineer",
    company: { name: "Invyo", website: "https://invyo.io" },
    location: "Casablanca",
    workplaceType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Own quality for an accounting platform used daily. Manual + automation blend, hybrid Casablanca.",
    responsibilities: [
      "Design and execute test strategies",
      "Build automated suites (Playwright/API)",
      "Champion quality culture",
    ],
    requirements: [
      "2+ years QA",
      "Test-automation with JS",
      "Systems thinking and empathy",
    ],
    skills: ["playwright", "javascript", "testing", "typescript", "cypress", "api testing"],
    salary: { min: 11000, max: 16000, currency: "MAD" },
    publishedAt: daysAgo(12, 12),
    fetchedAt: new Date().toISOString(),
    url: "https://invyo.io/careers/qa",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-036",
    source: "mock",
    title: "Site Reliability Engineer",
    company: { name: "Cloudrizon", website: "https://cloudrizon.com" },
    location: "Remote (Morocco)",
    workplaceType: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    description:
      "Make reliability a feature. SLOs, on-call, and resilience for cloud products, remote from Morocco.",
    responsibilities: [
      "Define and monitor SLOs",
      "Build resilience and chaos practices",
      "Improve incident response",
    ],
    requirements: [
      "4+ years SRE/DevOps",
      "Kubernetes, load, and reliability tooling",
      "Strong coding (Go/Python)",
    ],
    skills: ["kubernetes", "linux", "prometheus", "grafana", "go", "python", "terraform"],
    salary: { min: 1100, max: 1600, currency: "USD" },
    publishedAt: daysAgo(20, 9),
    fetchedAt: new Date().toISOString(),
    url: "https://cloudrizon.com/careers/sre",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-037",
    source: "mock",
    title: "Full Stack Developer — MERN",
    company: { name: "DigitalOcean-like studio", website: "https://studiopad.ma" },
    location: "Agadir",
    workplaceType: "onsite",
    employmentType: "full-time",
    experienceLevel: "mid-level",
    description:
      "Build web apps for clients across Europe and the GCC with a modern MERN stack. Onsite Agadir.",
    responsibilities: [
      "Build full-stack features (MERN)",
      "Own features from DB to UI",
      "Collaborate across time zones",
    ],
    requirements: [
      "2+ years MERN",
      "MongoDB, Express, React, Node",
      "Quality-driven and communicative",
    ],
    skills: ["mongodb", "express", "react", "node.js", "javascript", "git"],
    salary: { min: 12000, max: 17000, currency: "MAD" },
    publishedAt: daysAgo(13, 4),
    fetchedAt: new Date().toISOString(),
    url: "https://studiopad.ma/careers/mern",
    hasRemoteApplications: false,
  },
  {
    externalId: "mock-038",
    source: "mock",
    title: "Site Reliability Engineer (intern)",
    company: { name: "MedZ", website: "https://medz.ma" },
    location: "Casablanca",
    workplaceType: "onsite",
    employmentType: "internship",
    experienceLevel: "entry",
    description:
      "A paid internship in platform engineering: monitoring, CI/CD, and automation at industrial scale.",
    responsibilities: [
      "Learn SRE basics and monitoring",
      "Automate routine operations",
      "Support CI/CD improvements",
    ],
    requirements: [
      "Linux/scripting basics",
      "Curiosity about infra",
      "Some Python or Bash",
    ],
    skills: ["linux", "bash", "python", "docker", "git"],
    salary: { min: 3500, max: 5000, currency: "MAD" },
    publishedAt: daysAgo(27),
    fetchedAt: new Date().toISOString(),
    url: "https://medz.ma/careers/sre-intern",
    hasRemoteApplications: false,
  },
];

export const mockJobs = deduplicateJobs(RAW_JOBS.map(normalizeJob));

export function getMockJobs(): Job[] {
  return mockJobs;
}
