export type SkillAliasMap = Record<string, string>;

/**
 * Aliases map every known spelling/short-hand of a skill to one canonical
 * key. Add more aliases here over time — matching improves without touching
 * the scoring logic.
 */
export const SKILL_ALIASES: SkillAliasMap = {
  reactjs: "react",
  "react.js": "react",
  react: "react",
  "react native": "react native",
  reactnative: "react native",
  nextjs: "next.js",
  "next.js": "next.js",
  node: "node.js",
  nodejs: "node.js",
  "node.js": "node.js",
  ts: "typescript",
  typescript: "typescript",
  typescrip: "typescript",
  "type script": "typescript",
  js: "javascript",
  "js/es6": "javascript",
  javascript: "javascript",
  "es6": "javascript",
  "es2015": "javascript",
  "jquery": "jquery",
  html: "html",
  html5: "html",
  css: "css",
  css3: "css",
  "express.js": "express",
  expressjs: "express",
  express: "express",
  "mongoose": "mongodb",
  mongo: "mongodb",
  mongodb: "mongodb",
  "mongo db": "mongodb",
  postgres: "postgresql",
  postgresql: "postgresql",
  "postgres sql": "postgresql",
  mysql: "mysql",
  sql: "sql",
  sqlserver: "sql server",
  "sql server": "sql server",
  redis: "redis",
  graphql: "graphql",
  "graph ql": "graphql",
  rest: "rest apis",
  "rest api": "rest apis",
  "restful": "rest apis",
  apis: "apis",
  docker: "docker",
  kubernetes: "kubernetes",
  k8s: "kubernetes",
  aws: "aws",
  "amazon web services": "aws",
  "google cloud": "google cloud",
  gcp: "google cloud",
  "azure": "azure",
  terraform: "terraform",
  "ci/cd": "ci/cd",
  ci: "ci/cd",
  cd: "ci/cd",
  jenkins: "jenkins",
  github: "git",
  "github actions": "git",
  gitlab: "git",
  git: "git",
  gitscm: "git",
  java: "java",
  "c#": "c#",
  ".net": ".net",
  dotnet: ".net",
  "asp.net": ".net",
  "c#/.net": ".net",
  python: "python",
  "django": "django",
  flask: "flask",
  "fastapi": "fastapi",
  php: "php",
  laravel: "laravel",
  "php/laravel": "php",
  ruby: "ruby",
  "ruby on rails": "ruby",
  rails: "ruby",
  golang: "go",
  go: "go",
  kotlin: "kotlin",
  swift: "swift",
  "objective-c": "objective-c",
  "react.js/native": "react native",
  "c/c++": "c++",
  "c++": "c++",
  cpp: "c++",
  c: "c",
  dart: "dart",
  flutter: "flutter",
  vue: "vue.js",
  "vue.js": "vue.js",
  vuejs: "vue.js",
  angular: "angular",
  "angularjs": "angular",
  svelte: "svelte",
  figma: "figma",
  "ui/ux": "ui/ux",
  "ui design": "ui/ux",
  "ux design": "ui/ux",
  "product design": "ui/ux",
  "sketch": "ui/ux",
  photoshop: "photoshop",
  illustrator: "illustrator",
  agile: "agile",
  scrum: "agile",
  "project management": "project management",
  jira: "jira",
  linux: "linux",
  "linux/unix": "linux",
  bash: "bash",
  "shell": "bash",
  "shell scripting": "bash",
  "devops": "devops",
  "cloud": "cloud",
  "cloud computing": "cloud",
  "machine learning": "machine learning",
  ml: "machine learning",
  "data science": "data science",
  "data analysis": "data analysis",
  "data engineering": "data engineering",
  "big data": "big data",
  spark: "spark",
  "apache spark": "spark",
  kafka: "kafka",
  "dbt": "dbt",
  "power bi": "power bi",
  "tableau": "tableau",
  "excel": "excel",
  "sql/postgres": "sql",
  "software engineering": "software engineering",
  "software development": "software engineering",
  "web development": "web development",
  "full stack": "full stack",
  fullstack: "full stack",
  "frontend": "frontend",
  "front-end": "frontend",
  "backend": "backend",
  "back-end": "backend",
  "microservices": "microservices",
  "monorepo": "monorepo",
  "tailwind": "tailwind css",
  tailwindcss: "tailwind css",
  "tailwind css": "tailwind css",
  "shadcn/ui": "shadcn/ui",
  "storybook": "storybook",
  "jest": "jest",
  vitest: "vitest",
  "playwright": "playwright",
  cypress: "cypress",
  "testing": "testing",
  "unit testing": "testing",
  "tdd": "testing",
  "eslint": "eslint",
  prettier: "prettier",
  "webpack": "webpack",
  vite: "vite",
  "next": "next.js",
  "zustand": "zustand",
  redux: "redux",
  "redux-toolkit": "redux",
  "context api": "react",
  "react hooks": "react",
  hooks: "react",
};

/**
 * Normalizes any skill string to a canonical lowercase key, falling back to
 * the cleaned input when no alias exists.
 */
export function normalizeSkill(input: string): string {
  const cleaned = input.trim().toLowerCase().replace(/\s+/g, " ");
  return SKILL_ALIASES[cleaned] ?? cleaned;
}